<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Board extends \App\Entity\Board implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Board' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Board' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Board' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\Board' . "\0" . 'sujets', '' . "\0" . 'App\\Entity\\Board' . "\0" . 'produitServices', '' . "\0" . 'App\\Entity\\Board' . "\0" . 'moderators'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Board' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Board' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Board' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\Board' . "\0" . 'sujets', '' . "\0" . 'App\\Entity\\Board' . "\0" . 'produitServices', '' . "\0" . 'App\\Entity\\Board' . "\0" . 'moderators'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Board $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre(string $titre): \App\Entity\Board
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie(): ?\App\Entity\CategorieBoard
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(?\App\Entity\CategorieBoard $categorie): \App\Entity\Board
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getSujets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSujets', []);

        return parent::getSujets();
    }

    /**
     * {@inheritDoc}
     */
    public function addSujet(\App\Entity\Sujet $sujet): \App\Entity\Board
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSujet', [$sujet]);

        return parent::addSujet($sujet);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSujet(\App\Entity\Sujet $sujet): \App\Entity\Board
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSujet', [$sujet]);

        return parent::removeSujet($sujet);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduitServices(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduitServices', []);

        return parent::getProduitServices();
    }

    /**
     * {@inheritDoc}
     */
    public function addProduitService(\App\Entity\ProduitService $produitService): \App\Entity\Board
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProduitService', [$produitService]);

        return parent::addProduitService($produitService);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProduitService(\App\Entity\ProduitService $produitService): \App\Entity\Board
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProduitService', [$produitService]);

        return parent::removeProduitService($produitService);
    }

    /**
     * {@inheritDoc}
     */
    public function getModerators(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModerators', []);

        return parent::getModerators();
    }

    /**
     * {@inheritDoc}
     */
    public function addModerator(\App\Entity\Moderator $moderator): \App\Entity\Board
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addModerator', [$moderator]);

        return parent::addModerator($moderator);
    }

    /**
     * {@inheritDoc}
     */
    public function removeModerator(\App\Entity\Moderator $moderator): \App\Entity\Board
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeModerator', [$moderator]);

        return parent::removeModerator($moderator);
    }

}
