<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Sujet extends \App\Entity\Sujet implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Sujet' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Sujet' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Sujet' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Sujet' . "\0" . 'lien_image', '' . "\0" . 'App\\Entity\\Sujet' . "\0" . 'board', '' . "\0" . 'App\\Entity\\Sujet' . "\0" . 'commentaires', '' . "\0" . 'App\\Entity\\Sujet' . "\0" . 'notesujets'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Sujet' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Sujet' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Sujet' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Sujet' . "\0" . 'lien_image', '' . "\0" . 'App\\Entity\\Sujet' . "\0" . 'board', '' . "\0" . 'App\\Entity\\Sujet' . "\0" . 'commentaires', '' . "\0" . 'App\\Entity\\Sujet' . "\0" . 'notesujets'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Sujet $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre(string $titre): \App\Entity\Sujet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\Sujet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getLienImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLienImage', []);

        return parent::getLienImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setLienImage($lien_image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLienImage', [$lien_image]);

        return parent::setLienImage($lien_image);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoard(): ?\App\Entity\Board
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoard', []);

        return parent::getBoard();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoard(?\App\Entity\Board $board): \App\Entity\Sujet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoard', [$board]);

        return parent::setBoard($board);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaires(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaires', []);

        return parent::getCommentaires();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommentaire(\App\Entity\Commentaire $commentaire): \App\Entity\Sujet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommentaire', [$commentaire]);

        return parent::addCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommentaire(\App\Entity\Commentaire $commentaire): \App\Entity\Sujet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommentaire', [$commentaire]);

        return parent::removeCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotesujets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotesujets', []);

        return parent::getNotesujets();
    }

    /**
     * {@inheritDoc}
     */
    public function addNotesujet(\App\Entity\Notesujet $notesujet): \App\Entity\Sujet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNotesujet', [$notesujet]);

        return parent::addNotesujet($notesujet);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNotesujet(\App\Entity\Notesujet $notesujet): \App\Entity\Sujet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNotesujet', [$notesujet]);

        return parent::removeNotesujet($notesujet);
    }

    /**
     * {@inheritDoc}
     */
    public function RatedBy(\App\Entity\User $u): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'RatedBy', [$u]);

        return parent::RatedBy($u);
    }

    /**
     * {@inheritDoc}
     */
    public function NotePerso(\App\Entity\User $u): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'NotePerso', [$u]);

        return parent::NotePerso($u);
    }

    /**
     * {@inheritDoc}
     */
    public function NoteSujetMoyenne(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'NoteSujetMoyenne', []);

        return parent::NoteSujetMoyenne();
    }

}
