twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
<<<<<<< HEAD
    form_themes: [ 'bootstrap_4_layout.html.twig' ]
=======
    form_theme : 'bootstrap_4_layout.html.twig'
>>>>>>> 7b3193d94ae251b7445204f6f1e4d643dbedf883
