<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSWcU2jG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSWcU2jG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSWcU2jG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSWcU2jG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSWcU2jG\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SWcU2jG',
    'container.build_id' => '674255fb',
    'container.build_time' => 1614478895,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSWcU2jG');
