<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKHs4ygr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKHs4ygr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKHs4ygr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKHs4ygr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKHs4ygr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KHs4ygr',
    'container.build_id' => 'd4324f31',
    'container.build_time' => 1614471429,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKHs4ygr');
