<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUyNcfpp\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUyNcfpp/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUyNcfpp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUyNcfpp\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUyNcfpp\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UyNcfpp',
    'container.build_id' => 'b02978da',
    'container.build_time' => 1613939660,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUyNcfpp');
