<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin']], [], []],
    'aide' => [[], ['_controller' => 'App\\Controller\\AideController::index'], [], [['text', '/aide']], [], []],
    'categorieAide' => [[], ['_controller' => 'App\\Controller\\CategorieAideController::index'], [], [['text', '/categorieAide']], [], []],
    'categorie' => [[], ['_controller' => 'App\\Controller\\CategorieController::index'], [], [['text', '/categorie']], [], []],
    'list' => [[], ['_controller' => 'App\\Controller\\CategorieController::list'], [], [['text', '/AfficherCategorie']], [], []],
    'listAdmin' => [[], ['_controller' => 'App\\Controller\\CategorieController::listAdmin'], [], [['text', '/AfficherCategorieAdmin']], [], []],
    'AjouterCategorie' => [[], ['_controller' => 'App\\Controller\\CategorieController::AjouterCategorie'], [], [['text', '/AjouterCategorie']], [], []],
    'update' => [['id'], ['_controller' => 'App\\Controller\\CategorieController::update'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/updateC']], [], []],
    'delete' => [['id'], ['_controller' => 'App\\Controller\\CategorieController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/deleteC']], [], []],
    'comptes' => [[], ['_controller' => 'App\\Controller\\ComptesController::index'], [], [['text', '/comptes']], [], []],
    'demande' => [[], ['_controller' => 'App\\Controller\\DemandeController::index'], [], [['text', '/demande']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/index']], [], []],
    'welcome' => [[], ['_controller' => 'App\\Controller\\NavigationContrllerController::index'], [], [['text', '/HolidayHiatus']], [], []],
    'main' => [[], ['_controller' => 'App\\Controller\\SujetController::index'], [], [['text', '/main']], [], []],
    'Afficher' => [['idboard'], ['_controller' => 'App\\Controller\\SujetController::afficher'], [], [['variable', '/', '[^/]++', 'idboard'], ['text', '/AfficherSujet']], [], []],
    'AjouterSujet' => [['idboard'], ['_controller' => 'App\\Controller\\SujetController::AjouterSujet'], [], [['variable', '/', '[^/]++', 'idboard'], ['text', '/AjouterSujet']], [], []],
];
